In [1]:
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2
%matplotlib inline
import time

In [2]:
#to keep things in order, and to avoid to copy and paste everytime our functions if we want to use them in more than one folder,
#we can temporarily use this library. 
import sys

#in this way Python will search the implementations also in the path '../HelperFunctions'
sys.path.insert(0, '../HelperFunctions')
sys.path.insert(0, '../pre-processing/Clean_Data/')
sys.path.insert(0, '../Logit')

In [3]:
from proj1_helpers import *
from common_functions import *
from counters import *
from remove import *
from replace import *
from regressors import batch_iter
from functions_logistic import *

In [4]:
yb, input_data, ids = load_csv_data("../data/train.csv", sub_sample=False)

In [5]:
#this will surely be deleted, in this way we are sure that original_data is the original version of the data and we don't have
#to load them again
sys.path.insert(0, '../')
from implementations import *
from copy import deepcopy
originalData = deepcopy(input_data)
originalY = deepcopy(yb)
print(yb)


yb = convert_minus1_to_0(yb)
print(yb)

[ 1. -1. -1. ...  1. -1. -1.]
[1. 0. 0. ... 1. 0. 0.]


# Functions from lab 5

In [14]:
#Creation of tx

input_data = deepcopy(originalData)
print(input_data.shape)

#Clean the dataset
numInvalidValues = countInvalid(input_data,-999)
idxCols = np.where(numInvalidValues>0)[0]
input_data = replaceWithZero(input_data,-999,idxCols)

# Stocking the indexes of columns to remove
#idxCols = np.where(countInvalid(input_data,-999)>0)[0]
#input_data=removeColumns(input_data,0)
#print(input_data.shape)

#standardize
tx,_,_ = standardize(input_data)

#add ones
#tx = np.c_[np.ones((yb.shape[0], 1)), tx]
y = yb
#print(tx.shape)

(250000, 30)


In [20]:
#first tries with gradient descent

tx,te,y,y_te=split_data(tx,y,0.8)
#Y, TX = sample_data(y, tx, 10, 150000)
max_iter = 1000
w = np.ones(tx.shape[1])
gamma = 1e-5
tol = 1e-6
loss = 0
losses=np.array([])
for iter in range(max_iter):
    old_loss = loss
    loss, w = learning_by_gradient_descent(y, tx, w, gamma)
    #losses = np.asarray(losses)
    #losses = np.append(losses,loss)
    #if iter%100 ==0:
        #gamma=0.95*gamma
        #w_new = w
        
    if iter%50 == 0:
        if np.abs((old_loss - loss)/loss) < tol:
            gamma = 0.9*gamma
            

print(w)

logistic_labels=predict_logistic_labels(w,te)
#logistic_labels[]
logistic_accuracy=sum(logistic_labels==y_te)/len(y_te) 
print('accuracy =',logistic_accuracy)

[9.99957826e-01 9.99338305e-01 1.61369775e-04 ... 5.05527316e-01
 1.15336010e-02 4.07890580e-02]
logistic loss:  226336.65361528646
[9.99778265e-01 9.98199417e-01 3.91572479e-04 ... 5.64756280e-01
 1.88647060e-02 6.78989552e-02]
logistic loss:  200696.1837484723
[9.98911965e-01 9.95329467e-01 9.27971589e-04 ... 6.14046886e-01
 3.04790197e-02 1.09266182e-01]
logistic loss:  175913.32618484588
[0.99513666 0.98864674 0.00212364 ... 0.65155258 0.04832505 0.16798489]
logistic loss:  152521.39838324222
[0.98092095 0.97472069 0.00462222 ... 0.67605851 0.07454901 0.24368431]
logistic loss:  131236.42971708643
[0.93793782 0.94980223 0.00939304 ... 0.68651269 0.11077087 0.3303146 ]
logistic loss:  112743.64711666282
[0.84399832 0.91321367 0.01748387 ... 0.68172795 0.15698725 0.41687529]
logistic loss:  97455.9540691243
[0.70950313 0.87088007 0.02935752 ... 0.66063142 0.21066585 0.49189956]
logistic loss:  85380.26580202037
[0.58460608 0.83301443 0.04427337 ... 0.62363955 0.26709986 0.54858258]
l

[0.39185608 0.6576766  0.15745179 ... 0.22124345 0.71116616 0.39161296]
logistic loss:  37036.19647608783
[0.39324028 0.65800775 0.15732506 ... 0.22145315 0.71148711 0.39160047]
logistic loss:  37030.33081338448
[0.39461406 0.65833321 0.15720041 ... 0.22165981 0.71180305 0.39159659]
logistic loss:  37024.604201366936
[0.3959771  0.65865302 0.15707781 ... 0.22186335 0.71211411 0.39160052]
logistic loss:  37019.009710914834
[0.39732908 0.65896727 0.15695723 ... 0.22206368 0.71242043 0.39161151]
logistic loss:  37013.541026682884
[0.39866976 0.65927601 0.15683861 ... 0.22226073 0.71272215 0.39162887]
logistic loss:  37008.19237773608
[0.39999888 0.65957933 0.15672193 ... 0.22245446 0.71301938 0.39165199]
logistic loss:  37002.9584767069
[0.40131626 0.65987729 0.15660713 ... 0.22264481 0.71331225 0.39168027]
logistic loss:  36997.83446639194
[0.40262171 0.66016999 0.15649417 ... 0.22283176 0.71360086 0.39171319]
logistic loss:  36992.81587284545
[0.40391509 0.66045748 0.15638301 ... 0.2230

[0.46583042 0.6709719  0.15117116 ... 0.2293503  0.72686538 0.39505302]
logistic loss:  36786.625519915906
[0.46640735 0.67102181 0.15111527 ... 0.2293843  0.72698643 0.39508308]
logistic loss:  36784.90714602756
[0.46697743 0.67106951 0.1510597  ... 0.22941743 0.72710611 0.39511275]
logistic loss:  36783.20972803989
[0.46754075 0.67111502 0.15100445 ... 0.2294497  0.72722443 0.39514206]
logistic loss:  36781.53291968881
[0.46809739 0.67115837 0.15094953 ... 0.22948112 0.72734142 0.39517101]
logistic loss:  36779.87638184044
[0.46864743 0.67119959 0.15089492 ... 0.22951173 0.72745708 0.39519962]
logistic loss:  36778.239782311735
[0.46919096 0.6712387  0.15084062 ... 0.22954154 0.72757143 0.3952279 ]
logistic loss:  36776.62279569674
[0.46972805 0.67127572 0.15078663 ... 0.22957057 0.72768449 0.39525586]
logistic loss:  36775.025103198335
[0.47025878 0.67131068 0.15073294 ... 0.22959884 0.72779627 0.39528351]
logistic loss:  36773.446392465106
[0.47078324 0.67134361 0.15067955 ... 0.22

[0.49544549 0.66987623 0.14757023 ... 0.23047334 0.73317649 0.3968701 ]
logistic loss:  36696.59724622948
[0.49567803 0.66981504 0.14753197 ... 0.23047748 0.73322679 0.39689136]
logistic loss:  36695.840721901215
[0.49590796 0.66975305 0.14749387 ... 0.23048152 0.73327653 0.39691262]
logistic loss:  36695.0909813131
[0.4961353  0.66969026 0.14745593 ... 0.23048547 0.73332572 0.3969339 ]
logistic loss:  36694.34793995007
[0.49636008 0.66962668 0.14741815 ... 0.23048932 0.73337435 0.3969552 ]
logistic loss:  36693.61151463065
[0.49658235 0.66956234 0.14738053 ... 0.23049307 0.73342245 0.39697651]
logistic loss:  36692.881623482084
[0.49680212 0.66949723 0.14734307 ... 0.23049674 0.73347001 0.39699783]
logistic loss:  36692.15818591618
[0.49701942 0.66943137 0.14730577 ... 0.23050032 0.73351705 0.39701916]
logistic loss:  36691.44112260553
[0.49723429 0.66936477 0.14726862 ... 0.23050382 0.73356355 0.39704052]
logistic loss:  36690.73035546028
[0.49744676 0.66929743 0.14723162 ... 0.23050

[0.50763802 0.66338645 0.14500476 ... 0.23066348 0.73580273 0.39858355]
logistic loss:  36653.01779690196
[0.50773649 0.66328831 0.14497662 ... 0.23066562 0.73582352 0.39860617]
logistic loss:  36652.6112905754
[0.50783391 0.66318994 0.14494858 ... 0.23066778 0.73584406 0.3986288 ]
logistic loss:  36652.207646182665
[0.50793028 0.66309137 0.14492065 ... 0.23066996 0.73586436 0.39865143]
logistic loss:  36651.80683607129
[0.50802563 0.66299258 0.14489282 ... 0.23067214 0.73588443 0.39867408]
logistic loss:  36651.40883294176
[0.50811996 0.66289358 0.14486509 ... 0.23067435 0.73590426 0.39869673]
logistic loss:  36651.01360984201
[0.50821328 0.66279437 0.14483746 ... 0.23067657 0.73592387 0.3987194 ]
logistic loss:  36650.62114016217
[0.50830561 0.66269497 0.14480994 ... 0.23067881 0.73594324 0.39874207]
logistic loss:  36650.23139762926
[0.50839695 0.66259538 0.14478251 ... 0.23068106 0.7359624  0.39876474]
logistic loss:  36649.84435630204
[0.50848731 0.66249559 0.14475519 ... 0.230683

[0.51287929 0.65535061 0.14308664 ... 0.23088871 0.73686021 0.40035055]
logistic loss:  36628.21007914613
[0.51292221 0.65524565 0.14306528 ... 0.23089242 0.73686809 0.40037292]
logistic loss:  36627.96448367389
[0.51296468 0.6551407  0.14304399 ... 0.23089615 0.73687587 0.40039528]
logistic loss:  36627.72034464035
[0.5130067  0.65503577 0.14302277 ... 0.2308999  0.73688355 0.40041763]
logistic loss:  36627.477650853885
[0.51304828 0.65493086 0.14300163 ... 0.23090367 0.73689111 0.40043996]
logistic loss:  36627.23639123855
[0.51308941 0.65482596 0.14298055 ... 0.23090745 0.73689858 0.40046227]
logistic loss:  36626.996554832585
[0.51313011 0.65472109 0.14295955 ... 0.23091126 0.73690594 0.40048457]
logistic loss:  36626.758130786984
[0.51317038 0.65461624 0.14293861 ... 0.23091509 0.7369132  0.40050686]
logistic loss:  36626.52110836394
[0.51321022 0.65451142 0.14291775 ... 0.23091893 0.73692036 0.40052912]
logistic loss:  36626.28547693548
[0.51324963 0.65440662 0.14289696 ... 0.230

[0.51515465 0.64731747 0.14161614 ... 0.23122836 0.73722266 0.40203825]
logistic loss:  36612.71408092551
[0.51517291 0.6472177  0.14159961 ... 0.23123324 0.73722475 0.40205897]
logistic loss:  36612.55552815936
[0.51519096 0.64711803 0.14158312 ... 0.23123813 0.7372268  0.40207967]
logistic loss:  36612.39781750855
[0.5152088  0.64701847 0.14156669 ... 0.23124303 0.7372288  0.40210034]
logistic loss:  36612.240943583834
[0.51522643 0.64691901 0.1415503  ... 0.23124794 0.73723075 0.40212098]
logistic loss:  36612.08490104109
[0.51524386 0.64681966 0.14153397 ... 0.23125286 0.73723265 0.4021416 ]
logistic loss:  36611.929684580784
[0.51526109 0.64672042 0.1415177  ... 0.23125779 0.73723451 0.40216219]
logistic loss:  36611.77528894754
[0.51527812 0.64662129 0.14150147 ... 0.23126273 0.73723632 0.40218275]
logistic loss:  36611.62170892955
[0.51529495 0.64652226 0.14148529 ... 0.23126767 0.73723808 0.40220329]
logistic loss:  36611.46893935827
[0.51531158 0.64642335 0.14146917 ... 0.2312

[0.51607462 0.63988963 0.14046926 ... 0.23162911 0.73727268 0.40357025]
logistic loss:  36602.52120085896
[0.51608118 0.63979945 0.14045626 ... 0.23163439 0.73727219 0.40358873]
logistic loss:  36602.41499207066
[0.51608764 0.6397094  0.1404433  ... 0.23163968 0.73727167 0.40360718]
logistic loss:  36602.309310500925
[0.516094   0.63961949 0.14043038 ... 0.23164497 0.73727114 0.4036256 ]
logistic loss:  36602.20415318079
[0.51610025 0.63952971 0.1404175  ... 0.23165026 0.73727058 0.40364399]
logistic loss:  36602.09951716194
[0.51610641 0.63944007 0.14040466 ... 0.23165556 0.73727001 0.40366235]
logistic loss:  36601.99539951644
[0.51611247 0.63935056 0.14039185 ... 0.23166085 0.73726942 0.40368068]
logistic loss:  36601.89179733653
[0.51611843 0.63926119 0.14037908 ... 0.23166614 0.7372688  0.40369898]
logistic loss:  36601.78870773454
[0.51612429 0.63917195 0.14036635 ... 0.23167144 0.73726817 0.40371724]
logistic loss:  36601.686127842615
[0.51613005 0.63908285 0.14035366 ... 0.2316

[0.51633592 0.63326614 0.13956222 ... 0.23203925 0.73718616 0.4049207 ]
logistic loss:  36595.62019899614
[0.51633663 0.63318666 0.13955187 ... 0.23204441 0.73718459 0.40493682]
logistic loss:  36595.54753648001
[0.51633729 0.63310731 0.13954155 ... 0.23204957 0.73718301 0.40495292]
logistic loss:  36595.47521978175
[0.51633789 0.6330281  0.13953126 ... 0.23205472 0.73718142 0.40496898]
logistic loss:  36595.40324710768
[0.51633845 0.63294903 0.139521   ... 0.23205987 0.73717982 0.40498501]
logistic loss:  36595.33161667482
[0.51633895 0.63287009 0.13951077 ... 0.23206502 0.73717822 0.40500102]
logistic loss:  36595.260326710944
[0.51633941 0.63279129 0.13950057 ... 0.23207016 0.73717661 0.40501699]
logistic loss:  36595.18937545441
[0.51633981 0.63271262 0.13949039 ... 0.2320753  0.73717499 0.40503293]
logistic loss:  36595.11876115409
[0.51634016 0.6326341  0.13948025 ... 0.23208043 0.73717336 0.40504885]
logistic loss:  36595.04848206938
[0.51634046 0.6325557  0.13947013 ... 0.23208

[0.51626231 0.62747044 0.13883627 ... 0.23242722 0.73704636 0.40609084]
logistic loss:  36590.86839632815
[0.51626    0.62740133 0.13882794 ... 0.23243197 0.73704443 0.40610472]
logistic loss:  36590.818039838654
[0.51625766 0.62733235 0.13881963 ... 0.23243671 0.73704249 0.40611858]
logistic loss:  36590.76791640846
[0.5162553  0.62726349 0.13881135 ... 0.23244145 0.73704055 0.40613241]
logistic loss:  36590.718024889866
[0.51625291 0.62719477 0.13880309 ... 0.23244618 0.7370386  0.40614621]
logistic loss:  36590.66836414151
[0.51625049 0.62712617 0.13879485 ... 0.2324509  0.73703666 0.40615998]
logistic loss:  36590.618933028156
[0.51624804 0.6270577  0.13878663 ... 0.23245562 0.73703471 0.40617373]
logistic loss:  36590.569730420786
[0.51624557 0.62698936 0.13877844 ... 0.23246034 0.73703277 0.40618745]
logistic loss:  36590.52075519652
[0.51624308 0.62692114 0.13877027 ... 0.23246504 0.73703082 0.40620114]
logistic loss:  36590.47200623856
[0.51624055 0.62685305 0.13876212 ... 0.23

[0.51601531 0.62245164 0.13824938 ... 0.23277782 0.73689286 0.40709453]
logistic loss:  36587.561305763185
[0.51601145 0.62239201 0.13824262 ... 0.23278204 0.73689089 0.4071064 ]
logistic loss:  36587.52610602267
[0.51600757 0.6223325  0.13823587 ... 0.23278626 0.73688893 0.40711824]
logistic loss:  36587.491065948976
[0.51600367 0.6222731  0.13822914 ... 0.23279047 0.73688697 0.40713006]
logistic loss:  36587.45618478223
[0.51599976 0.62221381 0.13822243 ... 0.23279467 0.73688501 0.40714185]
logistic loss:  36587.421461766426
[0.51599584 0.62215464 0.13821573 ... 0.23279886 0.73688305 0.40715362]
logistic loss:  36587.3868961495
[0.51599191 0.62209558 0.13820906 ... 0.23280305 0.73688109 0.40716537]
logistic loss:  36587.35248718312
[0.51598796 0.62203664 0.1382024  ... 0.23280723 0.73687914 0.40717709]
logistic loss:  36587.31823412287
[0.515984   0.62197781 0.13819576 ... 0.23281141 0.73687718 0.40718879]
logistic loss:  36587.28413622809
[0.51598003 0.62191909 0.13818913 ... 0.2328

[0.51571278 0.61849026 0.13780986 ... 0.23306036 0.7367568  0.40787968]
logistic loss:  36585.41784454894
[0.51570907 0.61844819 0.1378053  ... 0.23306337 0.7367553  0.40788798]
logistic loss:  36585.397149259356
[0.51570536 0.61840619 0.13780074 ... 0.23306639 0.7367538  0.40789626]
logistic loss:  36585.37652893715
[0.51570165 0.61836426 0.1377962  ... 0.23306939 0.7367523  0.40790454]
logistic loss:  36585.355983299574
[0.51569793 0.6183224  0.13779166 ... 0.2330724  0.7367508  0.4079128 ]
logistic loss:  36585.33551206504
[0.51569421 0.6182806  0.13778714 ... 0.2330754  0.73674931 0.40792104]
logistic loss:  36585.31511495308
[0.51569048 0.61823887 0.13778262 ... 0.23307839 0.73674782 0.40792927]
logistic loss:  36585.29479168435
[0.51568675 0.6181972  0.13777811 ... 0.23308138 0.73674632 0.40793749]
logistic loss:  36585.27454198064
[0.51568301 0.6181556  0.13777362 ... 0.23308437 0.73674483 0.40794569]
logistic loss:  36585.25436556476
[0.51567928 0.61811407 0.13776913 ... 0.2330

[0.51543002 0.6155594  0.13749693 ... 0.23327104 0.73664996 0.40845612]
logistic loss:  36584.07499303507
[0.51542648 0.61552575 0.13749339 ... 0.23327347 0.73664871 0.40846271]
logistic loss:  36584.060722245806
[0.51542294 0.61549215 0.13748986 ... 0.23327589 0.73664746 0.4084693 ]
logistic loss:  36584.04649750888
[0.5154194  0.6154586  0.13748634 ... 0.2332783  0.73664621 0.40847587]
logistic loss:  36584.032318670244
[0.51541586 0.6154251  0.13748283 ... 0.23328071 0.73664496 0.40848244]
logistic loss:  36584.01818557639
[0.51541232 0.61539165 0.13747932 ... 0.23328312 0.73664371 0.40848899]
logistic loss:  36584.004098074394
[0.51540877 0.61535824 0.13747582 ... 0.23328553 0.73664247 0.40849553]
logistic loss:  36583.990056011826
[0.51540523 0.61532489 0.13747232 ... 0.23328793 0.73664122 0.40850207]
logistic loss:  36583.97605923682
[0.51540168 0.61529158 0.13746883 ... 0.23329033 0.73663998 0.40850859]
logistic loss:  36583.962107597996
[0.51539813 0.61525832 0.13746534 ... 0.2

In [6]:
#regularized logistic 

sys.path.insert(0, '../PROJECT_TO_SUBMIT/')
from implementations_new import *

lambdas = np.logspace(-6,0,15)
degrees = np.arange(15)
gamma = 1e-5

best_lambda_acc, best_degree_acc,accuracy = logistic_hyperparam_with_CV(y, tx, lambdas, gamma, degrees)
  
## recompute best w
x_augmented = build_poly(tx, best_degree_acc)
best_w_acc = learning_by_gradient_descent(y,x_augmented,best_lambda_acc)

    
    

NameError: name 'compute_loss_MSE' is not defined

In [7]:
from implementations_new import compute_loss_MSE

NameError: name 'compute_loss_MSE' is not defined

Let's try to generate a submission

In [ ]:
WWW = w 

In [ ]:
xxx, test_data, ids = load_csv_data("../data/test.csv", sub_sample=False)

In [ ]:
#we need to preprocess the test_data as we preprocessed the train data

numInvalidValues = countInvalid(test_data,-999)
idxCols = np.where(numInvalidValues>0)[0]
test_data = replaceWithZero(test_data,-999,idxCols)
txTest,_,_ = standardize(test_data)
txTest = np.c_[np.ones((xxx.shape[0], 1)), txTest]

In [ ]:
y_pred = predict_labels(WWW, txTest)

In [ ]:
create_csv_submission(ids, y_pred, 'submission.csv')

# Same thing with PCA

In [ ]:
sys.path.insert(0, '../pre-processing/PCA/')

In [ ]:
from pca_functions import PCAWithCovariance

input_data = deepcopy(originalData)
y = deepcopy(originalY)
print(input_data.shape)
print(y.shape)
numInvalidValues = countInvalid(input_data,-999)
idxCols = np.where(numInvalidValues>0)[0]
input_data = replaceWithZero(input_data,-999,idxCols)
input_data,_,_ = standardize(input_data)

In [ ]:
from pca_functions import PCAWithCovariance

input_data = deepcopy(originalData)
y = deepcopy(originalY)
print(input_data.shape)
print(y.shape)
input_data=removeColumns(input_data,0)
print(input_data.shape)
input_data,_,_ = standardize(input_data)

In [ ]:
#Generating the principal components

_,eV = PCAWithCovariance(input_data)

N = 7 #num p. components
components = np.empty(input_data.shape[0])
for i in range(N):
    components = np.c_[components, input_data.dot(eV[:,i])]
    
print(components.shape)
print(components[:,0])
tx = np.c_[np.ones(input_data.shape[0]), components]
print(tx.shape)
print(tx[:,0])
print(tx[:,1])

In [ ]:
Y, TX = sample_data(y, tx, 1, 70000)
TX.shape

In [ ]:
max_iter = 1000
w = np.ones(tx.shape[1])
gamma = 10000
loss0 = 0
for iter in range(max_iter):
    wold = w
    loss, w = learning_by_gradient_descent(yb, tx, w, gamma)
    #gamma=0.55*gamma
    if iter%10==0:
        wnew = w
        print(f'Iter = {iter}, Loss = {loss}, |wold - wnew| = {np.linalg.norm(wold-wnew)}')
print('final loss =',loss)

In [ ]:
# generate submission with PCA
xxx, test_data, ids = load_csv_data("../data/test.csv", sub_sample=False)



In [ ]:
numInvalidValues = countInvalid(test_data,-999)
idxCols = np.where(numInvalidValues>0)[0]
test_data = replaceWithZero(test_data,-999,idxCols)
test_data,_,_ = standardize(test_data)

components = np.empty(test_data.shape[0])
for i in range(N):
    components = np.c_[components, test_data.dot(eV[:,i])]
    
#tx_test = np.c_[np.ones(test_data.shape[0]), components]
tx_test = components

y_pred = predict_labels(w, tx_test)
create_csv_submission(ids, y_pred, 'submission.csv')