In [4]:
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2
%matplotlib inline
import time

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
#to keep things in order, and to avoid to copy and paste everytime our functions if we want to use them in more than one folder,
#we can temporarily use this library. 
import sys

#in this way Python will search the implementations also in the path '../HelperFunctions'
sys.path.insert(0, '../HelperFunctions')
sys.path.insert(0, '../pre-processing/Clean_Data/')
sys.path.insert(0, '../Logit')

In [6]:
from proj1_helpers import *
from common_functions import *
from counters import *
from remove import *
from replace import *
from regressors import batch_iter
from functions_logistic import *

In [7]:
yb, input_data, ids = load_csv_data("../data/train.csv", sub_sample=False)

In [8]:
#this will surely be deleted, in this way we are sure that original_data is the original version of the data and we don't have
#to load them again
from copy import deepcopy
originalData = deepcopy(input_data)
originalY = deepcopy(yb)
print(yb)


[ 1. -1. -1. ...  1. -1. -1.]


# Functions from lab 5

In [9]:
#Creation of tx

input_data = deepcopy(originalData)
print(input_data.shape)

#Clean the dataset
numInvalidValues = countInvalid(input_data,-999)
idxCols = np.where(numInvalidValues>0)[0]
input_data = replaceWithZero(input_data,-999,idxCols)

# Stocking the indexes of columns to remove
#idxCols = np.where(countInvalid(input_data,-999)>0)[0]
#input_data=removeColumns(input_data,0)
#print(input_data.shape)

#standardize
tx,_,_ = standardize(input_data)

#add ones
#tx = np.c_[np.ones((yb.shape[0], 1)), tx]
y = yb
#print(tx.shape)

(250000, 30)


In [10]:
#To understand better standardization
A=[[1.3,4.7,8],[0.4,5,6],[2,5,1.2]]
print(A)
print(np.mean(A,axis=0))
print(A-np.mean(A,axis=0))
a=A-np.mean(A,axis=0)
b=np.std(A,axis=0)
print('std =',b)
print(a/np.std(A,axis=0))

[[1.3, 4.7, 8], [0.4, 5, 6], [2, 5, 1.2]]
[1.23333333 4.9        5.06666667]
[[ 0.06666667 -0.2         2.93333333]
 [-0.83333333  0.1         0.93333333]
 [ 0.76666667  0.1        -3.86666667]]
std = [0.65489609 0.14142136 2.85345794]
[[ 0.10179732 -1.41421356  1.02799249]
 [-1.2724665   0.70710678  0.32708852]
 [ 1.17066918  0.70710678 -1.35508101]]


In [ ]:
#first tries with gradient descent

#Y, TX = sample_data(y, tx, 10, 150000)
max_iter = 100000
w = np.ones(tx.shape[1])
gamma = 10000
loss0 = 0

for iter in range(max_iter):
    w_old = w
    loss, w = learning_by_gradient_descent(y, tx, w, gamma)
    print('w =',w)
    
    if iter%100==0:
        #gamma=0.55*gamma
        w_new = w
        print('iter = ', iter)
        #print(f'Iter = {iter}, Loss = {loss}, |w_old - w_new| = {np.linalg.norm(w_old-w_new)}')




[9.99964004e-01 7.17746986e-01 9.97774477e-01 ... 9.51513627e-03
 1.21004458e-04 9.62364309e-04]
logistic loss:  1517221.8143192923
logistic loss corection only:  8059047.825479169
w = [ 1.19646931e+07 -7.63094089e+08 -2.74885465e+08 -2.48389333e+08
 -1.09840309e+08 -1.27675713e+07 -2.51572509e+08  2.74338611e+08
 -3.85924426e+08 -4.47691227e+08 -6.35997594e+08  1.23449145e+08
 -7.74947729e+07  2.31451424e+08 -1.55818545e+08 -6.51484190e+07
 -5.06381694e+08 -1.58066303e+08 -2.67771458e+07 -3.87551018e+08
 -5.27945146e+07 -4.41630101e+08 -5.40739418e+08 -3.50639025e+08
 -1.46500871e+08 -4.70662105e+07 -4.57160688e+08 -4.72738516e+07
 -4.97217240e+07 -4.67421683e+08]
iter =  0
[0. 1. 0. ... 1. 1. 1.]
logistic loss:  4445886.537178324
logistic loss corection only:  8059047.825479169
w = [ 5.52979284e+08 -1.45796478e+09 -1.99836927e+08  9.10592238e+08
  9.68634097e+08  9.96721477e+08 -7.67576414e+08 -1.00855026e+08
 -4.03639746e+07  7.14956951e+08 -7.49537444e+08  1.12702566e+09
  9.645304

w = [ 1.06178051e+09 -2.71157280e+09 -1.18160798e+09  1.16260210e+09
  1.38916866e+09  2.54657630e+09 -1.82818565e+09  1.41361309e+09
 -8.99338084e+08  4.90418946e+07 -1.22880750e+09  1.11330418e+09
  1.40759629e+09  2.18857254e+09 -4.11969034e+07 -5.18072029e+07
  5.62345141e+08 -3.13322196e+06  1.76298917e+07  5.80654256e+07
  1.80608678e+07 -2.82690673e+08 -9.24632537e+08  1.66388360e+08
  3.19072808e+06 -1.17280459e+07 -5.91112969e+08 -2.01999340e+06
 -3.40368647e+07 -5.69134418e+08]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2232195.0305502163
logistic loss corection only:  8059047.825479169
w = [ 1.09973066e+09 -2.79287526e+09 -1.25587313e+09  1.21438001e+09
  1.43097027e+09  2.66756607e+09 -1.87799190e+09  1.48608433e+09
 -9.22386948e+08  4.80338504e+07 -1.26032345e+09  1.14322927e+09
  1.44666492e+09  2.26903752e+09 -4.30305356e+07 -5.20740227e+07
  6.03775347e+08 -3.11438762e+06  1.91869155e+07  7.04779177e+07
  1.91781285e+07 -2.97146006e+08 -9.61716973e+08  1.68924016e+08
  4.0

w = [ 1.62403489e+09 -3.87729912e+09 -2.18031182e+09  1.87503094e+09
  1.96512746e+09  4.22874209e+09 -2.51315606e+09  2.40470599e+09
 -1.24172949e+09  3.87390707e+07 -1.73833314e+09  1.56586921e+09
  1.95489881e+09  3.33053670e+09 -6.47534660e+07 -5.74333111e+07
  1.07866407e+09 -6.98971040e+05  3.39807493e+07  1.83612478e+08
  3.21708416e+07 -4.75104304e+08 -1.39158817e+09  2.15832372e+08
  6.41064095e+06 -4.22069083e+06 -9.29968435e+08  9.89249600e+06
 -4.19777478e+07 -9.58647826e+08]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2215271.0300117107
logistic loss corection only:  8059047.825479169
w = [ 1.66564583e+09 -3.96192126e+09 -2.24902335e+09  1.92521060e+09
  2.00603160e+09  4.34849868e+09 -2.56229456e+09  2.47421419e+09
 -1.26737420e+09  3.82085219e+07 -1.77760852e+09  1.59922900e+09
  1.99445055e+09  3.41266560e+09 -6.60157026e+07 -5.80376128e+07
  1.11271678e+09 -2.66337792e+05  3.49893124e+07  1.90211165e+08
  3.30250786e+07 -4.88353099e+08 -1.42262850e+09  2.20131899e+08
  6.7

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2209855.3498393884
logistic loss corection only:  8059047.825479169
w = [ 2.24625206e+09 -5.15834582e+09 -3.20435991e+09  2.62473026e+09
  2.57836372e+09  6.02186954e+09 -3.25655891e+09  3.42979569e+09
 -1.63230986e+09  3.01339579e+07 -2.33920081e+09  2.07313618e+09
  2.55597057e+09  4.56289716e+09 -8.75650280e+07 -7.03642455e+07
  1.57508502e+09  4.72535722e+06  4.83524851e+07  2.67242780e+08
  4.35194049e+07 -6.71663751e+08 -1.84605529e+09  2.83932346e+08
  8.77457140e+06 -1.01400055e+06 -1.29009558e+09  1.57891369e+07
 -5.64905433e+07 -1.36234760e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2209694.1688818787
logistic loss corection only:  8059047.825479169
w = [ 2.28800185e+09 -5.24424406e+09 -3.27164113e+09  2.67453281e+09
  2.61919089e+09  6.14122852e+09 -3.30668559e+09  3.49738089e+09
 -1.65864580e+09  2.96013187e+07 -2.37984285e+09  2.10710927e+09
  2.59645893e+09  4.64524072e+09 -8.91333772e+07 -7.13472092e+07
  1.60768804e+09  4.9006042

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2207405.399285243
logistic loss corection only:  8059047.825479169
w = [ 2.83469197e+09 -6.36423717e+09 -4.13694406e+09  3.32190647e+09
  3.14907369e+09  7.69189228e+09 -3.96279890e+09  4.37049911e+09
 -2.00619302e+09  2.30995426e+07 -2.90964955e+09  2.55301827e+09
  3.12439846e+09  5.71589685e+09 -1.08869208e+08 -8.62640883e+07
  2.02804602e+09  5.25256324e+06  6.27653669e+07  3.31232964e+08
  5.50795997e+07 -8.52191909e+08 -2.26257175e+09  3.53389197e+08
  1.12774084e+07 -2.82399430e+06 -1.62967374e+09  1.91462369e+07
 -6.86429397e+07 -1.73626314e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2207373.163093741
logistic loss corection only:  8059047.825479169
w = [ 2.87687008e+09 -6.45058395e+09 -4.20300509e+09  3.37165775e+09
  3.18990420e+09  7.81116206e+09 -4.01352252e+09  4.43732656e+09
 -2.03303551e+09  2.26314036e+07 -2.95050816e+09  2.58740403e+09
  3.16531606e+09  5.79828044e+09 -1.10398952e+08 -8.73982332e+07
  2.06019471e+09  5.20788575e

logistic loss:  2205890.298284653
logistic loss corection only:  8059047.825479169
w = [ 3.42262587e+09 -7.57763258e+09 -5.06024537e+09  4.01728816e+09
  3.72045232e+09  9.36101373e+09 -4.67517769e+09  5.30302122e+09
 -2.38309569e+09  1.48980816e+07 -3.48140927e+09  3.03620495e+09
  3.69977696e+09  6.86733791e+09 -1.30231177e+08 -1.02633552e+08
  2.47555794e+09  5.77444854e+06  7.71093110e+07  3.88506116e+08
  6.55836091e+07 -1.03326800e+09 -2.67600420e+09  4.23493681e+08
  1.32333776e+07 -5.41393446e+06 -1.97082004e+09  2.24865269e+07
 -8.00086156e+07 -2.10997328e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2205922.5344761554
logistic loss corection only:  8059047.825479169
w = [ 3.46455140e+09 -7.66447418e+09 -5.12593239e+09  4.06696306e+09
  3.76123656e+09  9.48017914e+09 -4.72622527e+09  5.36935627e+09
 -2.41002838e+09  1.43248768e+07 -3.52226807e+09  3.07082487e+09
  3.74099753e+09  6.94967276e+09 -1.31713470e+08 -1.03858579e+08
  2.50752493e+09  5.83358724e+06  7.80309592e+07  3.

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2205277.8106461167
logistic loss corection only:  8059047.825479169
w = [ 4.00993148e+09 -8.79515220e+09 -5.97731046e+09  4.71332079e+09
  4.29080339e+09  1.10286560e+10 -5.39036597e+09  6.22975965e+09
 -2.76170466e+09  7.71014032e+06 -4.05562303e+09  3.52170031e+09
  4.27812487e+09  8.02068260e+09 -1.50614294e+08 -1.19428964e+08
  2.92136585e+09  7.36372760e+06  8.98328617e+07  4.44140439e+08
  7.48359988e+07 -1.21341603e+09 -3.08880683e+09  4.94845084e+08
  1.53934079e+07 -6.87631011e+06 -2.31228674e+09  2.58437544e+07
 -9.39670147e+07 -2.48253864e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2205084.393497105
logistic loss corection only:  8059047.825479169
w = [ 4.05197834e+09 -8.88227287e+09 -6.04257359e+09  4.76304743e+09
  4.33147807e+09  1.11477156e+10 -5.44151171e+09  6.29583667e+09
 -2.78883939e+09  7.20868436e+06 -4.09677522e+09  3.55643334e+09
  4.31947864e+09  8.10308943e+09 -1.51917917e+08 -1.20508265e+08
  2.95307943e+09  7.51061511

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2204955.4487310974
logistic loss corection only:  8059047.825479169
w = [ 4.59759214e+09 -1.00158621e+10 -6.89071589e+09  5.40962996e+09
  4.86038810e+09  1.26954616e+10 -6.10774328e+09  7.15346096e+09
 -3.14253277e+09  9.06149350e+05 -4.63196038e+09  4.00740229e+09
  4.85808833e+09  9.17390656e+09 -1.69960824e+08 -1.33578330e+08
  3.36455389e+09  8.93621481e+06  1.02511393e+08  4.99600818e+08
  8.41159947e+07 -1.39303431e+09 -3.50203276e+09  5.66973042e+08
  1.67702794e+07 -8.34384512e+06 -2.65336435e+09  2.79115125e+07
 -1.07577531e+08 -2.85403338e+09]
iter =  100
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2204858.740156592
logistic loss corection only:  8059047.825479169
w = [ 4.63959796e+09 -1.01031238e+10 -6.95579963e+09  5.45932386e+09
  4.90113060e+09  1.28145448e+10 -6.15913819e+09  7.21941329e+09
 -3.16987951e+09  4.02064531e+05 -4.67306724e+09  4.04210181e+09
  4.89963911e+09  9.25612053e+09 -1.71395097e+08 -1.34717342e+08
  3.39616338e+09

logistic loss:  2204020.5991775417
logistic loss corection only:  8059047.825479169
w = [ 5.18483241e+09 -1.12396786e+10 -7.80178172e+09  6.10569681e+09
  5.43014814e+09  1.43618692e+10 -6.82851234e+09  8.07504216e+09
 -3.52670309e+09 -5.92955233e+06 -5.20781420e+09  4.49362135e+09
  5.44045383e+09  1.03244930e+10 -1.89228087e+08 -1.49903492e+08
  3.80572059e+09  8.76723334e+06  1.15819371e+08  5.54143143e+08
  9.52634150e+07 -1.57207913e+09 -3.91611873e+09  6.39787647e+08
  1.88587467e+07 -1.12731458e+07 -2.99301910e+09  3.05810642e+07
 -1.20277320e+08 -3.22450741e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2204117.3077520477
logistic loss corection only:  8059047.825479169
w = [ 5.22675012e+09 -1.13272280e+10 -7.86679639e+09  6.15541865e+09
  5.47078995e+09  1.44808256e+10 -6.88014305e+09  8.14081546e+09
 -3.55414075e+09 -6.44819128e+06 -5.24895303e+09  4.52838612e+09
  5.48211282e+09  1.04066457e+10 -1.90578773e+08 -1.51093309e+08
  3.83714520e+09  8.71495488e+06  1.16784833e+08  5

logistic loss:  2203311.4029645
logistic loss corection only:  8059047.825479169
w = [ 5.77126841e+09 -1.24655530e+10 -8.70906283e+09  6.80171048e+09
  5.99935063e+09  1.60270385e+10 -7.55279623e+09  8.99616670e+09
 -3.90959311e+09 -1.32514982e+07 -5.78416076e+09  4.98017363e+09
  6.02518792e+09  1.14755458e+10 -2.09505463e+08 -1.67031273e+08
  4.24531162e+09  7.04970023e+06  1.29785284e+08  6.09908076e+08
  1.06282374e+08 -1.74964397e+09 -4.32972342e+09  7.11895389e+08
  2.07387039e+07 -1.34082515e+07 -3.33352963e+09  3.31657232e+07
 -1.33954928e+08 -3.59530738e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2203246.9305814956
logistic loss corection only:  8059047.825479169
w = [ 5.81310053e+09 -1.25530811e+10 -8.77372385e+09  6.85136805e+09
  6.04004773e+09  1.61459745e+10 -7.60463962e+09  9.06196041e+09
 -3.93696087e+09 -1.38451490e+07 -5.82536052e+09  5.01493601e+09
  6.06710229e+09  1.15577737e+10 -2.10999272e+08 -1.68289474e+08
  4.27662586e+09  6.94789209e+06  1.30801064e+08  6.13

logistic loss:  2202763.387708967
logistic loss corection only:  8059047.825479169
w = [ 6.35685930e+09 -1.36916620e+10 -9.61426310e+09  7.49670612e+09
  6.56883254e+09  1.76917723e+10 -8.27898829e+09  9.91642183e+09
 -4.29362781e+09 -2.14905088e+07 -6.36118547e+09  5.46746024e+09
  6.61227764e+09  1.26266576e+10 -2.31123125e+08 -1.83897761e+08
  4.68325361e+09  5.10651756e+06  1.43726671e+08  6.64796094e+08
  1.17287265e+08 -1.92705123e+09 -4.74344257e+09  7.83504702e+08
  2.24759308e+07 -1.44964029e+07 -3.67513047e+09  3.58262103e+07
 -1.47192910e+08 -3.96683220e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2202763.3877089676
logistic loss corection only:  8059047.825479169
w = [ 6.39877871e+09 -1.37792124e+10 -9.67879799e+09  7.54636752e+09
  6.60952019e+09  1.78106918e+10 -8.33096195e+09  9.98211326e+09
 -4.32109206e+09 -2.20294638e+07 -6.40236503e+09  5.50230869e+09
  6.65426275e+09  1.27088648e+10 -2.32691171e+08 -1.85051873e+08
  4.71458159e+09  5.02275301e+06  1.44699717e+08  6.

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2202666.679134461
logistic loss corection only:  8059047.825479169
w = [ 6.94326239e+09 -1.49178169e+10 -1.05180500e+10  8.19173045e+09
  7.13845876e+09  1.93566223e+10 -9.00678943e+09  1.08357326e+10
 -4.67809160e+09 -2.91362198e+07 -6.93787293e+09  5.95575979e+09
  7.20027870e+09  1.37773529e+10 -2.52427079e+08 -2.00684731e+08
  5.12125885e+09  4.24494609e+06  1.57326520e+08  7.19049845e+08
  1.27057740e+08 -2.10374368e+09 -5.15709714e+09  8.56240261e+08
  2.39932943e+07 -1.46963376e+07 -4.01645211e+09  3.87738128e+07
 -1.60128423e+08 -4.33757565e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2202602.2067514574
logistic loss corection only:  8059047.825479169
w = [ 6.98510477e+09 -1.50054410e+10 -1.05826143e+10  8.24137139e+09
  7.17916564e+09  1.94755452e+10 -9.05878993e+09  1.09013091e+10
 -4.70555644e+09 -2.96710545e+07 -6.97907186e+09  5.99066902e+09
  7.24228983e+09  1.38595588e+10 -2.53923944e+08 -2.01910293e+08
  5.15254035e+09  4.16852164

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2202215.3724534344
logistic loss corection only:  8059047.825479169
w = [ 7.53058584e+09 -1.61448506e+10 -1.14198589e+10  8.88693738e+09
  7.70845021e+09  2.10215397e+10 -9.73517846e+09  1.17544423e+10
 -5.06265447e+09 -3.65795274e+07 -7.51442388e+09  6.44452082e+09
  7.78862745e+09  1.49278598e+10 -2.72409158e+08 -2.17157978e+08
  5.55924944e+09  2.86895432e+06  1.70516475e+08  7.73357894e+08
  1.36396055e+08 -2.28035936e+09 -5.57029068e+09  9.29214619e+08
  2.51278003e+07 -1.48996427e+07 -4.35753461e+09  4.23018429e+07
 -1.73202580e+08 -4.70803378e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2202312.0810279404
logistic loss corection only:  8059047.825479169
w = [ 7.57256209e+09 -1.62325747e+10 -1.14841547e+10  8.93659293e+09
  7.74918566e+09  2.11404610e+10 -9.78725104e+09  1.18201022e+10
 -5.09014776e+09 -3.71362344e+07 -7.55558513e+09  6.47940600e+09
  7.83070127e+09  1.50099619e+10 -2.73865558e+08 -2.18261927e+08
  5.59049643e+09  2.7601542

w = [ 8.15945055e+09 -1.74607630e+10 -1.23843234e+10  9.63125585e+09
  8.31942282e+09  2.28053734e+10 -1.05164448e+10  1.27388745e+10
 -5.47515676e+09 -4.54891461e+07 -8.13250375e+09  6.96744341e+09
  8.41979401e+09  1.61598252e+10 -2.93849454e+08 -2.33473526e+08
  6.02689695e+09  1.67827697e+06  1.84617004e+08  8.31651883e+08
  1.46408903e+08 -2.47042478e+09 -6.01355390e+09  1.00696779e+09
  2.64581203e+07 -1.48177121e+07 -4.72367432e+09  4.66324920e+07
 -1.87483813e+08 -5.10552525e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2202150.9000704307
logistic loss corection only:  8059047.825479169
w = [ 8.20129423e+09 -1.75485097e+10 -1.24486371e+10  9.68085754e+09
  8.36016603e+09  2.29243090e+10 -1.05685389e+10  1.28044469e+10
 -5.50267863e+09 -4.60895358e+07 -8.17372684e+09  7.00225225e+09
  8.46190325e+09  1.62419774e+10 -2.95270945e+08 -2.34578617e+08
  6.05805164e+09  1.58593120e+06  1.85579472e+08  8.35543404e+08
  1.47055221e+08 -2.48308924e+09 -6.04314122e+09  1.01213481e+09
  2.6

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201925.2467299174
logistic loss corection only:  8059047.825479169
w = [ 8.78782616e+09 -1.87769877e+10 -1.33478523e+10  1.03752457e+10
  8.93097321e+09  2.45895955e+10 -1.12981970e+10  1.37226147e+10
 -5.88736232e+09 -5.44342370e+07 -8.75114643e+09  7.48973976e+09
  9.05148517e+09  1.73921686e+10 -3.15432855e+08 -2.50463650e+08
  6.49373715e+09  6.89725108e+05  1.99723061e+08  8.89889907e+08
  1.56762623e+08 -2.66015949e+09 -6.45699615e+09  1.08454334e+09
  2.84974981e+07 -1.56238920e+07 -5.08954680e+09  5.06951133e+07
 -2.02425191e+08 -5.50296332e+09]
iter =  200
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201925.246729917
logistic loss corection only:  8059047.825479169
w = [ 8.82968510e+09 -1.88647470e+10 -1.34120758e+10  1.04248367e+10
  8.97175298e+09  2.47085435e+10 -1.13503455e+10  1.37881952e+10
 -5.91485270e+09 -5.50432550e+07 -8.79241778e+09  7.52453991e+09
  9.09361076e+09  1.74743156e+10 -3.16863233e+08 -2.51591522e+08
  6.52480980e+09

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201699.593389404
logistic loss corection only:  8059047.825479169
w = [ 9.37308384e+09 -2.00059626e+10 -1.42475465e+10  1.10696270e+10
  9.50158982e+09  2.62547502e+10 -1.20286325e+10  1.46399542e+10
 -6.27232913e+09 -6.28285544e+07 -9.32902931e+09  7.97755198e+09
  9.64140082e+09  1.85420960e+10 -3.35901374e+08 -2.66398888e+08
  6.92866125e+09  4.79196695e+04  2.13721886e+08  9.44321787e+08
  1.66932146e+08 -2.83704784e+09 -6.87092823e+09  1.15737472e+09
  3.05669856e+07 -1.67179366e+07 -5.43136808e+09  5.47457504e+07
 -2.16015932e+08 -5.87372126e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201699.593389404
logistic loss corection only:  8059047.825479169
w = [ 9.41485508e+09 -2.00937666e+10 -1.43118092e+10  1.11192172e+10
  9.54232981e+09  2.63736714e+10 -1.20808437e+10  1.47054626e+10
 -6.29983780e+09 -6.34408175e+07 -9.37029745e+09  8.01241933e+09
  9.68354979e+09  1.86242171e+10 -3.37393817e+08 -2.67535393e+08
  6.95973781e+09 -9.23150229e

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201570.648623396
logistic loss corection only:  8059047.825479169
w = [ 9.95835990e+09 -2.12354733e+10 -1.51465179e+10  1.17642453e+10
  1.00721813e+10  2.79197776e+10 -1.27596971e+10  1.55566193e+10
 -6.65711010e+09 -7.12060535e+07 -9.90684901e+09  8.46565032e+09
  1.02318746e+10  1.96916749e+10 -3.56771087e+08 -2.82357353e+08
  7.36360136e+09 -3.58909294e+05  2.27286503e+08  9.98637024e+08
  1.77166147e+08 -3.01380235e+09 -7.28515169e+09  1.23058454e+09
  3.23321375e+07 -1.75492369e+07 -5.77349797e+09  5.96882536e+07
 -2.29395579e+08 -6.24438329e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201602.8848148985
logistic loss corection only:  8059047.825479169
w = [ 1.00001932e+10 -2.13233196e+10 -1.52106979e+10  1.18138793e+10
  1.01129415e+10  2.80387070e+10 -1.28119275e+10  1.56220933e+10
 -6.68458279e+09 -7.17995162e+07 -9.94811939e+09  8.50052066e+09
  1.02740575e+10  1.97737668e+10 -3.58259470e+08 -2.83521865e+08
  7.39467197e+09 -3.91067791

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201441.7038573883
logistic loss corection only:  8059047.825479169
w = [ 1.05446089e+10 -2.24654436e+10 -1.60442830e+10  1.24594159e+10
  1.06427516e+10  2.95847344e+10 -1.34911211e+10  1.64734117e+10
 -7.04170456e+09 -7.93632062e+07 -1.04842462e+10  8.95391000e+09
  1.08224737e+10  2.08408325e+10 -3.77650883e+08 -2.98696128e+08
  7.79891789e+09 -9.42414336e+05  2.40854073e+08  1.05324811e+09
  1.87665808e+08 -3.19070072e+09 -7.69924279e+09  1.30399002e+09
  3.39648129e+07 -1.84810397e+07 -6.11525431e+09  6.49452751e+07
 -2.42471963e+08 -6.61477360e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201473.94004889
logistic loss corection only:  8059047.825479169
w = [ 1.05865046e+10 -2.25533262e+10 -1.61083872e+10  1.25090834e+10
  1.06834966e+10  2.97036509e+10 -1.35433651e+10  1.65389007e+10
 -7.06917045e+09 -7.99432681e+07 -1.05254786e+10  8.98880226e+09
  1.08646533e+10  2.09229039e+10 -3.79159817e+08 -2.99865376e+08
  7.83001989e+09 -9.85632064e

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.11310873e+10 -2.36958848e+10 -1.69415025e+10  1.31547441e+10
  1.12130740e+10  3.12494508e+10 -1.42224441e+10  1.73900913e+10
 -7.42641757e+09 -8.74174658e+07 -1.10616947e+10  9.44252956e+09
  1.14129198e+10  2.19901518e+10 -3.99008435e+08 -3.15296428e+08
  8.23440365e+09 -1.65400745e+06  2.54407325e+08  1.10763505e+09
  1.98125346e+08 -3.36758760e+09 -8.11330598e+09  1.37743566e+09
  3.57386409e+07 -1.98002250e+07 -6.45693974e+09  7.03573350e+07
 -2.55757052e+08 -6.98511753e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201377.2314743847
logistic loss corection only:  8059047.825479169
w = [ 1.11729759e+10 -2.37837840e+10 -1.70055773e+10  1.32044032e+10
  1.12538076e+10  3.13683455e+10 -1.42746705e+10  1.74555656e+10
 -7.45391628e+09 -8.80074891e+07 -1.11029547e+10  9.47742649e+09
  1.14551015e+10  2.20722525e+10 -4.00525946e+08 -3.16496615e+08
  8.26551169e+09 -1.69320494

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201183.814325373
logistic loss corection only:  8059047.825479169
w = [ 1.17170366e+10 -2.49265745e+10 -1.78389581e+10  1.38502757e+10
  1.17834065e+10  3.29139445e+10 -1.49540936e+10  1.83062686e+10
 -7.81111799e+09 -9.54104829e+07 -1.16392193e+10  9.93154179e+09
  1.20037923e+10  2.31394927e+10 -4.19545860e+08 -3.32387939e+08
  8.66972208e+09 -2.42875254e+06  2.67569228e+08  1.16159914e+09
  2.08361712e+08 -3.54387713e+09 -8.52738431e+09  1.45073765e+09
  3.77549789e+07 -2.09510098e+07 -6.79855373e+09  7.58676527e+07
 -2.68656069e+08 -7.35535642e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201216.0505168755
logistic loss corection only:  8059047.825479169
w = [ 1.17588883e+10 -2.50144827e+10 -1.79030576e+10  1.38999557e+10
  1.18241396e+10  3.30328280e+10 -1.50063753e+10  1.83717065e+10
 -7.83859420e+09 -9.59903994e+07 -1.16804643e+10  9.96647320e+09
  1.20459993e+10  2.32215852e+10 -4.20993417e+08 -3.33628405e+08
  8.70082318e+09 -2.49513978

logistic loss:  2201248.2867083773
logistic loss corection only:  8059047.825479169
w = [ 1.23030799e+10 -2.61573250e+10 -1.87362036e+10  1.45457471e+10
  1.23536263e+10  3.45782784e+10 -1.56860253e+10  1.92224489e+10
 -8.19599165e+09 -1.03531420e+08 -1.22166587e+10  1.04204877e+10
  1.25946492e+10  2.42888135e+10 -4.40069894e+08 -3.49687685e+08
  9.10516900e+09 -3.43103218e+06  2.80560336e+08  1.21533495e+09
  2.18467241e+08 -3.72010448e+09 -8.94168816e+09  1.52388914e+09
  3.93981372e+07 -2.19763176e+07 -7.14040398e+09  8.09667264e+07
 -2.81712797e+08 -7.72577064e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201248.2867083773
logistic loss corection only:  8059047.825479169
w = [ 1.23449313e+10 -2.62452273e+10 -1.88002822e+10  1.45954231e+10
  1.23943546e+10  3.46971580e+10 -1.57383057e+10  1.92878813e+10
 -8.22348424e+09 -1.04109685e+08 -1.22579131e+10  1.04554109e+10
  1.26368517e+10  2.43709296e+10 -4.41555736e+08 -3.50929900e+08
  9.13627202e+09 -3.52004818e+06  2.81498791e+08  1

logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.28889404e+10 -2.73880785e+10 -1.96333533e+10  1.52411933e+10
  1.29237783e+10  3.62425569e+10 -1.64179400e+10  2.01384115e+10
 -8.58091209e+09 -1.11641125e+08 -1.27943010e+10  1.09094277e+10
  1.31854438e+10  2.54384340e+10 -4.61050970e+08 -3.66994991e+08
  9.54054276e+09 -4.68461149e+06  2.93806850e+08  1.26922637e+09
  2.28807741e+08 -3.89646605e+09 -9.35611179e+09  1.59702943e+09
  4.10551273e+07 -2.32089752e+07 -7.48232900e+09  8.60662398e+07
 -2.94769459e+08 -8.09622366e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.29308126e+10 -2.74760115e+10 -1.96974026e+10  1.52908667e+10
  1.29644968e+10  3.63614286e+10 -1.64702179e+10  2.02038444e+10
 -8.60841163e+09 -1.12216857e+08 -1.28355665e+10  1.09443512e+10
  1.32276374e+10  2.55205492e+10 -4.62564570e+08 -3.68231205e+08
  9.57163761e+09 -4.76489205e+06  2.94771556e+08  1.2

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201377.2314743847
logistic loss corection only:  8059047.825479169
w = [ 1.34748690e+10 -2.86191735e+10 -2.05302378e+10  1.59365288e+10
  1.34938508e+10  3.79067647e+10 -1.71498440e+10  2.10544233e+10
 -8.96580454e+09 -1.19819842e+08 -1.33721916e+10  1.13983414e+10
  1.37761672e+10  2.65880584e+10 -4.82251805e+08 -3.84149835e+08
  9.97563155e+09 -5.69708715e+06  3.07218475e+08  1.32294637e+09
  2.39498666e+08 -4.07283230e+09 -9.77046040e+09  1.67021102e+09
  4.30291887e+07 -2.46609615e+07 -7.82436608e+09  9.11794677e+07
 -3.07795232e+08 -8.46669491e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201409.4676658865
logistic loss corection only:  8059047.825479169
w = [ 1.35167087e+10 -2.87071006e+10 -2.05943034e+10  1.59861930e+10
  1.35345724e+10  3.80256329e+10 -1.72021319e+10  2.11198413e+10
 -8.99327836e+09 -1.20417863e+08 -1.34134788e+10  1.14332538e+10
  1.38183652e+10  2.66701862e+10 -4.83776672e+08 -3.85361782e+08
  1.00067062e+10 -5.7528495

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201344.995282883
logistic loss corection only:  8059047.825479169
w = [ 1.40607450e+10 -2.98501786e+10 -2.14268187e+10  1.66317095e+10
  1.40640174e+10  3.95709749e+10 -1.78820824e+10  2.19704409e+10
 -9.35051481e+09 -1.28224890e+08 -1.39501545e+10  1.18870902e+10
  1.43670063e+10  2.77376906e+10 -5.03535215e+08 -4.01170013e+08
  1.04105938e+10 -6.27851392e+06  3.20943636e+08  1.37662524e+09
  2.50592792e+08 -4.24917006e+09 -1.01850703e+10  1.74315895e+09
  4.53072268e+07 -2.62246545e+07 -8.16673236e+09  9.66135545e+07
 -3.20583617e+08 -8.83740661e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201344.995282883
logistic loss corection only:  8059047.825479169
w = [ 1.41025739e+10 -2.99381271e+10 -2.14908558e+10  1.66813666e+10
  1.41047493e+10  3.96898566e+10 -1.79343847e+10  2.20358504e+10
 -9.37798403e+09 -1.28814338e+08 -1.39914318e+10  1.19220200e+10
  1.44092132e+10  2.78198055e+10 -5.05034903e+08 -4.02384791e+08
  1.04416693e+10 -6.31248957e

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.46463005e+10 -3.10815254e+10 -2.23234030e+10  1.73270271e+10
  1.46342227e+10  4.12352133e+10 -1.86144144e+10  2.28860013e+10
 -9.73504198e+09 -1.36598591e+08 -1.45279364e+10  1.23761848e+10
  1.49578854e+10  2.88872275e+10 -5.24620415e+08 -4.18137100e+08
  1.08456565e+10 -6.66885910e+06  3.34681551e+08  1.43018912e+09
  2.61648358e+08 -4.42533178e+09 -1.05997640e+10  1.81616666e+09
  4.77572929e+07 -2.78879445e+07 -8.50912072e+09  1.02117896e+08
 -3.33412627e+08 -9.20808216e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201280.522899879
logistic loss corection only:  8059047.825479169
w = [ 1.46881263e+10 -3.11694839e+10 -2.23874431e+10  1.73767079e+10
  1.46749528e+10  4.13540875e+10 -1.86667254e+10  2.29513795e+10
 -9.76252559e+09 -1.37190189e+08 -1.45691911e+10  1.24111195e+10
  1.50000923e+10  2.89693338e+10 -5.26116297e+08 -4.19338139e+08
  1.08767444e+10 -6.67107138e

logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.52318228e+10 -3.23129979e+10 -2.32199980e+10  1.80225434e+10
  1.52044341e+10  4.28994447e+10 -1.93467663e+10  2.38012453e+10
 -1.01197653e+10 -1.44910205e+08 -1.51054627e+10  1.28653818e+10
  1.55487734e+10  3.00366868e+10 -5.45511788e+08 -4.34820887e+08
  1.12808881e+10 -6.62510253e+06  3.48047108e+08  1.48379957e+09
  2.72479667e+08 -4.60154359e+09 -1.10145400e+10  1.88927671e+09
  5.00316019e+07 -2.94006492e+07 -8.85155161e+09  1.07648599e+08
 -3.46180016e+08 -9.57870469e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.52736445e+10 -3.24009550e+10 -2.32840360e+10  1.80722287e+10
  1.52451691e+10  4.30183229e+10 -1.93990786e+10  2.38666043e+10
 -1.01472397e+10 -1.45495642e+08 -1.51467078e+10  1.29003448e+10
  1.55909848e+10  3.01187968e+10 -5.46999294e+08 -4.35990646e+08
  1.13119862e+10 -6.61755583e+06  3.48986389e+08  1.4

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201344.995282883
logistic loss corection only:  8059047.825479169
w = [ 1.58588907e+10 -3.36324134e+10 -2.41805710e+10  1.87676323e+10
  1.58153477e+10  4.46825781e+10 -2.01315799e+10  2.47815883e+10
 -1.05318955e+10 -1.53795544e+08 -1.57243911e+10  1.33896857e+10
  1.61819929e+10  3.12684138e+10 -5.67964709e+08 -4.52507750e+08
  1.17472062e+10 -6.62933930e+06  3.62218410e+08  1.54101198e+09
  2.84201403e+08 -4.79036463e+09 -1.14589955e+10  1.96757470e+09
  5.25192111e+07 -3.11080368e+07 -9.21846397e+09  1.13861720e+08
 -3.60074943e+08 -9.97581372e+09]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201344.995282883
logistic loss corection only:  8059047.825479169
w = [ 1.59006889e+10 -3.37203759e+10 -2.42446092e+10  1.88173003e+10
  1.58560726e+10  4.48014527e+10 -2.01839040e+10  2.48469435e+10
 -1.05593712e+10 -1.54390416e+08 -1.57656591e+10  1.34246359e+10
  1.62242087e+10  3.13505308e+10 -5.69464973e+08 -4.53690279e+08
  1.17782904e+10 -6.63246872e

w = [ 1.64858758e+10 -3.49518141e+10 -2.51411167e+10  1.95126533e+10
  1.64262083e+10  4.64656931e+10 -2.09164854e+10  2.57619060e+10
 -1.09440255e+10 -1.62748494e+08 -1.63433525e+10  1.39140456e+10
  1.68152524e+10  3.25001377e+10 -5.90328111e+08 -4.70364368e+08
  1.22134855e+10 -6.63198370e+06  3.76487162e+08  1.59814313e+09
  2.95746394e+08 -4.97917082e+09 -1.19035758e+10  2.04582985e+09
  5.49985705e+07 -3.26891232e+07 -9.58547565e+09  1.20103176e+08
 -3.74026599e+08 -1.03729931e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201248.2867083773
logistic loss corection only:  8059047.825479169
w = [ 1.65276715e+10 -3.50397593e+10 -2.52051435e+10  1.95623184e+10
  1.64669366e+10  4.65845720e+10 -2.09688304e+10  2.58272468e+10
 -1.09715132e+10 -1.63347215e+08 -1.63846080e+10  1.39489913e+10
  1.68574815e+10  3.25822565e+10 -5.91798252e+08 -4.71587990e+08
  1.22445785e+10 -6.63324369e+06  3.77473174e+08  1.60195654e+09
  2.96489266e+08 -4.99175263e+09 -1.19332301e+10  2.05105210e+09
  5.5

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.71128094e+10 -3.62711722e+10 -2.61015634e+10  2.02575793e+10
  1.70370208e+10  4.82487842e+10 -2.17016324e+10  2.67420948e+10
 -1.13563154e+10 -1.71854738e+08 -1.69622324e+10  1.44382958e+10
  1.74485875e+10  3.37318172e+10 -6.12434046e+08 -4.88698248e+08
  1.26797559e+10 -6.65575591e+06  3.91047904e+08  1.65517205e+09
  3.06713221e+08 -5.16798922e+09 -1.23485076e+10  2.12409429e+09
  5.71391839e+07 -3.38438108e+07 -9.95273460e+09  1.26033122e+08
 -3.88153099e+08 -1.07703413e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201280.522899879
logistic loss corection only:  8059047.825479169
w = [ 1.71546086e+10 -3.63591270e+10 -2.61655883e+10  2.03072486e+10
  1.70777442e+10  4.83676590e+10 -2.17539761e+10  2.68074334e+10
 -1.13837991e+10 -1.72453466e+08 -1.70034908e+10  1.44732468e+10
  1.74908122e+10  3.38139334e+10 -6.13921287e+08 -4.89938613e+08
  1.27108454e+10 -6.65766013e

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201248.2867083773
logistic loss corection only:  8059047.825479169
w = [ 1.76980308e+10 -3.75026000e+10 -2.69978987e+10  2.09528592e+10
  1.76071128e+10  4.99130048e+10 -2.24344018e+10  2.76569145e+10
 -1.17411114e+10 -1.80343915e+08 -1.75399988e+10  1.49275257e+10
  1.80396979e+10  3.48814100e+10 -6.33188876e+08 -5.05838686e+08
  1.31148299e+10 -6.62212104e+06  4.04459525e+08  1.70840965e+09
  3.16808118e+08 -5.34425070e+09 -1.27637853e+10  2.19718490e+09
  5.90419281e+07 -3.47491384e+07 -1.02954990e+10  1.31593311e+08
 -4.01357038e+08 -1.11411685e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.77398276e+10 -3.75905474e+10 -2.70619248e+10  2.10025269e+10
  1.76478410e+10  5.00318836e+10 -2.24867468e+10  2.77222470e+10
 -1.17685978e+10 -1.80941105e+08 -1.75812711e+10  1.49624640e+10
  1.80819270e+10  3.49635319e+10 -6.34674536e+08 -5.07070648e+08
  1.31459100e+10 -6.61785526

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.82833745e+10 -3.87340154e+10 -2.78941136e+10  2.16481444e+10
  1.81772252e+10  5.15772460e+10 -2.31671075e+10  2.85717315e+10
 -1.21259545e+10 -1.88805171e+08 -1.81178578e+10  1.54167257e+10
  1.86308216e+10  3.60310474e+10 -6.53981694e+08 -5.22925807e+08
  1.35498512e+10 -6.50836253e+06  4.17817022e+08  1.76167046e+09
  3.26885295e+08 -5.52050632e+09 -1.31790227e+10  2.27030563e+09
  6.09391259e+07 -3.56216512e+07 -1.06382205e+10  1.37204518e+08
 -4.14599408e+08 -1.15119611e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201248.2867083773
logistic loss corection only:  8059047.825479169
w = [ 1.83251639e+10 -3.88219761e+10 -2.79581528e+10  2.16978029e+10
  1.82179438e+10  5.16961169e+10 -2.32194501e+10  2.86370680e+10
 -1.21534459e+10 -1.89416794e+08 -1.81591368e+10  1.54516737e+10
  1.86730419e+10  3.61131604e+10 -6.55459545e+08 -5.24141667e+08
  1.35809162e+10 -6.49529807

w = [ 1.89105230e+10 -4.00533624e+10 -2.88543345e+10  2.23930471e+10
  1.87880466e+10  5.33603502e+10 -2.39521534e+10  2.95518962e+10
 -1.25383132e+10 -1.97882665e+08 -1.87369896e+10  1.59408355e+10
  1.92641568e+10  3.72628381e+10 -6.76266481e+08 -5.41154560e+08
  1.40160060e+10 -6.35373661e+06  4.32094671e+08  1.81870833e+09
  3.37726337e+08 -5.70939073e+09 -1.36239749e+10  2.34860386e+09
  6.30046978e+07 -3.65750802e+07 -1.10054390e+10  1.43211132e+08
 -4.28783533e+08 -1.19092748e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 1.89523235e+10 -4.01413119e+10 -2.89183574e+10  2.24427010e+10
  1.88287652e+10  5.34792211e+10 -2.40044960e+10  2.96172419e+10
 -1.25658041e+10 -1.98492084e+08 -1.87782639e+10  1.59757760e+10
  1.93063770e+10  3.73449599e+10 -6.77745839e+08 -5.42364618e+08
  1.40470883e+10 -6.34465641e+06  4.33045964e+08  1.82250726e+09
  3.38445316e+08 -5.72198565e+09 -1.36536492e+10  2.35381616e+09
  6.31

w = [ 1.94957387e+10 -4.12847459e+10 -2.97505488e+10  2.30882339e+10
  1.93580958e+10  5.50244638e+10 -2.46848461e+10  3.04665880e+10
 -1.29234538e+10 -2.06452867e+08 -1.93149427e+10  1.64299869e+10
  1.98552006e+10  3.84126794e+10 -6.96979035e+08 -5.58004286e+08
  1.44510774e+10 -6.18799991e+06  4.45568011e+08  1.87196392e+09
  3.48043446e+08 -5.88579677e+09 -1.40393517e+10  2.42155514e+09
  6.50250269e+07 -3.75164732e+07 -1.13483302e+10  1.48784931e+08
 -4.42117856e+08 -1.22802538e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201248.2867083773
logistic loss corection only:  8059047.825479169
w = [ 1.95375834e+10 -4.13727133e+10 -2.98145163e+10  2.31378874e+10
  1.93988136e+10  5.51433171e+10 -2.47371548e+10  3.05319241e+10
 -1.29510128e+10 -2.07077500e+08 -1.93562457e+10  1.64649328e+10
  1.98974120e+10  3.84948244e+10 -6.98475972e+08 -5.59195038e+08
  1.44821370e+10 -6.18477739e+06  4.46546585e+08  1.87576529e+09
  3.48788004e+08 -5.89841433e+09 -1.40690051e+10  2.42675405e+09
  6.5

w = [ 2.00810739e+10 -4.25162888e+10 -3.06466283e+10  2.37834692e+10
  1.99282246e+10  5.66884582e+10 -2.54173600e+10  3.13810524e+10
 -1.33091232e+10 -2.15207847e+08 -1.98930960e+10  1.69193210e+10
  2.04462637e+10  3.95625566e+10 -7.17757048e+08 -5.74822877e+08
  1.48857895e+10 -6.02055556e+06  4.59416918e+08  1.92527544e+09
  3.58482987e+08 -6.06237881e+09 -1.44544314e+10  2.49438605e+09
  6.72568620e+07 -3.85287752e+07 -1.16913233e+10  1.54409731e+08
 -4.55784126e+08 -1.26513784e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 2.01228527e+10 -4.26042367e+10 -3.07106667e+10  2.38331197e+10
  1.99689512e+10  5.68073104e+10 -2.54697060e+10  3.14463633e+10
 -1.33366691e+10 -2.15840542e+08 -1.99343852e+10  1.69542662e+10
  2.04885030e+10  3.96446905e+10 -7.19247707e+08 -5.76029432e+08
  1.49168489e+10 -6.02903283e+06  4.60413246e+08  1.92907528e+09
  3.59235684e+08 -6.07500357e+09 -1.44840848e+10  2.49957479e+09
  6.74

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201248.2867083773
logistic loss corection only:  8059047.825479169
w = [ 2.07083042e+10 -4.38356159e+10 -3.16066984e+10  2.45283818e+10
  2.05391975e+10  5.84712980e+10 -2.62022940e+10  3.23607432e+10
 -1.37221843e+10 -2.24603283e+08 -2.05123865e+10  1.74440235e+10
  2.10799276e+10  4.07944516e+10 -7.40059568e+08 -5.92440521e+08
  1.53516498e+10 -6.14450130e+06  4.74216499e+08  1.98240031e+09
  3.69594946e+08 -6.25163189e+09 -1.48991103e+10  2.57236966e+09
  6.96183392e+07 -3.94646820e+07 -1.20587316e+10  1.60299866e+08
 -4.70185554e+08 -1.30490249e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201312.759091381
logistic loss corection only:  8059047.825479169
w = [ 2.07500874e+10 -4.39235534e+10 -3.16707274e+10  2.45780327e+10
  2.05799422e+10  5.85901551e+10 -2.62546453e+10  3.24260482e+10
 -1.37497226e+10 -2.25233318e+08 -2.05536707e+10  1.74789888e+10
  2.11221976e+10  4.08765764e+10 -7.41528005e+08 -5.93616836e+08
  1.53827096e+10 -6.17585640

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201216.0505168755
logistic loss corection only:  8059047.825479169
w = [ 2.12935872e+10 -4.50669254e+10 -3.25026834e+10  2.52235214e+10
  2.11095766e+10  6.01352728e+10 -2.69349592e+10  3.32752186e+10
 -1.41076753e+10 -2.33453652e+08 -2.10904635e+10  1.79337032e+10
  2.16716458e+10  4.19442073e+10 -7.60656750e+08 -6.08971137e+08
  1.57863203e+10 -6.43553285e+06  4.87856205e+08  2.03576755e+09
  3.80049892e+08 -6.42826544e+09 -1.53141118e+10  2.64505926e+09
  7.16296996e+07 -4.05390765e+07 -1.24016243e+10  1.65840803e+08
 -4.83478628e+08 -1.34202249e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201248.2867083773
logistic loss corection only:  8059047.825479169
w = [ 2.13354294e+10 -4.51548846e+10 -3.25666354e+10  2.52731758e+10
  2.11503146e+10  6.02541264e+10 -2.69872744e+10  3.33405531e+10
 -1.41352083e+10 -2.34082967e+08 -2.11317650e+10  1.79686729e+10
  2.17139070e+10  4.20263459e+10 -7.62140977e+08 -6.10158304e+08
  1.58173696e+10 -6.4491010

[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201216.0505168755
logistic loss corection only:  8059047.825479169
w = [ 2.19207476e+10 -4.63862678e+10 -3.34624809e+10  2.59683307e+10
  2.17206754e+10  6.19180902e+10 -2.77198662e+10  3.42550780e+10
 -1.45206473e+10 -2.42946735e+08 -2.17099159e+10  1.84583665e+10
  2.23056030e+10  4.31761491e+10 -7.82766058e+08 -6.26801675e+08
  1.62519544e+10 -6.72370907e+06  5.02439211e+08  2.09298839e+09
  3.91247231e+08 -6.61748047e+09 -1.57587652e+10  2.72293383e+09
  7.38276647e+07 -4.16860881e+07 -1.27690077e+10  1.71841600e+08
 -4.97769200e+08 -1.38179465e+10]
[0. 1. 0. ... 0. 1. 0.]
logistic loss:  2201216.0505168755
logistic loss corection only:  8059047.825479169
w = [ 2.19625041e+10 -4.64742181e+10 -3.35265238e+10  2.60179798e+10
  2.17614153e+10  6.20369434e+10 -2.77722162e+10  3.43203854e+10
 -1.45481733e+10 -2.43588742e+08 -2.17512077e+10  1.84933482e+10
  2.23478686e+10  4.32582688e+10 -7.84220180e+08 -6.27991084e+08
  1.62829897e+10 -6.7470284

Let's try to generate a submission

In [ ]:
WWW = w 

In [ ]:
xxx, test_data, ids = load_csv_data("../data/test.csv", sub_sample=False)

In [ ]:
#we need to preprocess the test_data as we preprocessed the train data

numInvalidValues = countInvalid(test_data,-999)
idxCols = np.where(numInvalidValues>0)[0]
test_data = replaceWithZero(test_data,-999,idxCols)
txTest,_,_ = standardize(test_data)
txTest = np.c_[np.ones((xxx.shape[0], 1)), txTest]

In [ ]:
y_pred = predict_labels(WWW, txTest)

In [ ]:
create_csv_submission(ids, y_pred, 'submission.csv')

# Same thing with PCA

In [ ]:
sys.path.insert(0, '../pre-processing/PCA/')

In [ ]:
from pca_functions import PCAWithCovariance

input_data = deepcopy(originalData)
y = deepcopy(originalY)
print(input_data.shape)
print(y.shape)
numInvalidValues = countInvalid(input_data,-999)
idxCols = np.where(numInvalidValues>0)[0]
input_data = replaceWithZero(input_data,-999,idxCols)
input_data,_,_ = standardize(input_data)

In [ ]:
from pca_functions import PCAWithCovariance

input_data = deepcopy(originalData)
y = deepcopy(originalY)
print(input_data.shape)
print(y.shape)
input_data=removeColumns(input_data,0)
print(input_data.shape)
input_data,_,_ = standardize(input_data)

In [ ]:
#Generating the principal components

_,eV = PCAWithCovariance(input_data)

N = 7 #num p. components
components = np.empty(input_data.shape[0])
for i in range(N):
    components = np.c_[components, input_data.dot(eV[:,i])]
    
print(components.shape)
print(components[:,0])
tx = np.c_[np.ones(input_data.shape[0]), components]
print(tx.shape)
print(tx[:,0])
print(tx[:,1])

In [ ]:
Y, TX = sample_data(y, tx, 1, 70000)
TX.shape

In [ ]:
max_iter = 1000
w = np.ones(tx.shape[1])
gamma = 10000
loss0 = 0
for iter in range(max_iter):
    wold = w
    loss, w = learning_by_gradient_descent(yb, tx, w, gamma)
    #gamma=0.55*gamma
    if iter%10==0:
        wnew = w
        print(f'Iter = {iter}, Loss = {loss}, |wold - wnew| = {np.linalg.norm(wold-wnew)}')
print('final loss =',loss)

In [ ]:
# generate submission with PCA
xxx, test_data, ids = load_csv_data("../data/test.csv", sub_sample=False)



In [ ]:
numInvalidValues = countInvalid(test_data,-999)
idxCols = np.where(numInvalidValues>0)[0]
test_data = replaceWithZero(test_data,-999,idxCols)
test_data,_,_ = standardize(test_data)

components = np.empty(test_data.shape[0])
for i in range(N):
    components = np.c_[components, test_data.dot(eV[:,i])]
    
#tx_test = np.c_[np.ones(test_data.shape[0]), components]
tx_test = components

y_pred = predict_labels(w, tx_test)
create_csv_submission(ids, y_pred, 'submission.csv')