In [20]:
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2
%matplotlib inline
import time 

#to keep things in order, and to avoid to copy and paste everytime our functions if we want to use them in more than one folder,
#we can temporarily use this library. 
import sys

#in this way Python will search the implementations also in the path '../HelperFunctions'
sys.path.insert(0, '../HelperFunctions')
sys.path.insert(0, '../pre-processing/Clean_Data/')

from proj1_helpers import *
from common_functions import *
from counters import *
from remove import *
from replace import *
from regressors import batch_iter

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Loading data

In [21]:
yb, input_data, ids = load_csv_data("../data/train.csv", sub_sample=False)

#this will surely be deleted, in this way we are sure that original_data is the original version of the data and we don't have
#to load them again
from copy import deepcopy
originalData = deepcopy(input_data)
originalY = deepcopy(yb)
print(yb)

# change the label of -1 to 0 for simplicity. 
idx_wrong=np.where(yb==-1)
print(idx_wrong)
yb[idx_wrong]=0
print(yb)

[ 1. -1. -1. ...  1. -1. -1.]
(array([     1,      2,      3, ..., 249996, 249998, 249999]),)
[1. 0. 0. ... 1. 0. 0.]


# Pre-processing

In [22]:
sys.path.insert(0, '../pre-processing/PCA/')

from pca_functions import PCAWithCovariance

input_data = deepcopy(originalData)
y = deepcopy(originalY)
print(input_data.shape)
print(y.shape)
input_data=removeColumns(input_data,0)
input_data.shape
input_data,_,_ = standardize(input_data)

(250000, 30)
(250000,)


### Creating new features based on PCA

In [27]:
#Generating the principal components

_,eV = PCAWithCovariance(input_data)

N = 7 #num p. components
components = np.empty(input_data.shape[0])
for i in range(N):
    components = np.c_[components, input_data.dot(eV[:,i])]
    
print(components.shape)
print(components[:,0])
tx = np.c_[np.ones(input_data.shape[0]), components]
print(tx.shape)
print(tx[:,0])
print(tx[:,1])

(250000, 8)
[1. 1. 1. ... 1. 1. 1.]
(250000, 9)
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]


In [ ]:
sys.path.insert(0, '../')
from implementations import *

# define parameter
lambdas = np.logspace(-5, 0, 15)
degree=3
    
# form tx
tx_tr = build_poly(input_data, degree)
print(tx_tr.shape)

# ridge regression with different lambda
rmse_tr = []
for ind, lambda_ in enumerate(lambdas):
    # ridge regression
    weight = ridge_regression(yb, tx_tr, lambda_)
    rmse_tr.append(np.sqrt(2 * compute_loss_MSE(yb, tx_tr, weight)))

    print("proportion={p}, degree={d}, lambda={l:.3f}, Training RMSE={tr:.3f}, Testing RMSE={te:.3f}".format(
          p=ratio, d=degree, l=lambda_, tr=rmse_tr[ind], te=rmse_te[ind]))

plot_train_test(rmse_tr, rmse_te, lambdas, degree)
    


(250000, 58)
